# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf4825b18f8fbe68eff3134ad72e1a2eedc06ed6a2bad9fd98581c5971708b1abafc543c7b4bc84dc12331e826988059938d092dc5c3ad53ff73e5010b135d3f

test:
  secret_key_base: a12b54a4a5edc777897585a66f0e3fa7101bd10b3ecc5ac9d55590a498287d657568a1f10c724ea64074eabaccb9b96072babfa1064c6ef7e35f66f4af45c5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
